name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Koyeb CLI
        run: |
          curl https://downloads.koyeb.com/koyeb-cli/releases/v3/koyeb-cli_3.3.1_linux_amd64.tar.gz -O
          tar xf koyeb-cli_3.3.1_linux_amd64.tar.gz
          sudo mv koyeb /usr/local/bin/
      
      - name: Login to Koyeb
        run: koyeb login ${{ secrets.KOYEB }}
      
      - name: Deploy to Koyeb
        run: |
          koyeb service update telescopy-bot \
            --env TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" \
            --env VIDEO_STORAGE="${{ secrets.VIDEO_STORAGE }}"
