name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env and zip project
        run: |
          mkdir -p deploy_env
          cp -r * deploy_env/
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> deploy_env/.env
          echo "VIDEO_STORAGE=${{ secrets.VIDEO_STORAGE }}" >> deploy_env/.env
          zip -r deploy_env.zip deploy_env

      - name: Install dependencies
        run: pip install requests

      - name: Upload and deploy to PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          echo "Uploading to PythonAnywhere..."

          curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/files/path/home/${PA_USERNAME}/deploy_env.zip" \
            -H "Authorization: Token ${PA_TOKEN}" \
            -F "file=@deploy_env.zip"

          echo "Running unzip and pip install on PythonAnywhere..."
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/bash_tasks/" \
            -H "Authorization: Token ${PA_TOKEN}" \
            -H "Content-Type: application/json" \
            --data "{\"command\": \"unzip -o ~/deploy_env.zip -d ~/ && pip3 install -r ~/deploy_env/requirements.txt\"}"

          echo "Launching bot in background..."
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/bash_tasks/" \
            -H "Authorization: Token ${PA_TOKEN}" \
            -H "Content-Type: application/json" \
            --data "{\"command\": \"cd ~/deploy_env && export \$(cat .env | xargs) && nohup python3 main.py &\"}"
