name: Deploy to PythonAnywhere via API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python packages
        run: pip install requests

      - name: Upload and run on PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          VIDEO_STORAGE: ${{ secrets.VIDEO_STORAGE }}
        run: |
          echo "Uploading files to PythonAnywhere..."

          mkdir deploy_env
          cp -r * deploy_env/
          echo "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}" >> deploy_env/.env
          echo "VIDEO_STORAGE=${VIDEO_STORAGE}" >> deploy_env/.env

          zip -r deploy_env.zip deploy_env

          python3 <<EOF
import requests

username = '${PA_USERNAME}'
token = '${PA_TOKEN}'

# Upload ZIP
print("Uploading ZIP...")
files = {'file': open('deploy_env.zip', 'rb')}
upload = requests.post(
    f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path/home/{username}/deploy_env.zip',
    headers={'Authorization': f'Token {token}'},
    files=files
)
print("Upload status:", upload.status_code, upload.content)

# Unzip via bash task
print("Unzipping on server...")
bash = requests.post(
    f'https://www.pythonanywhere.com/api/v0/user/{username}/bash_tasks/',
    headers={'Authorization': f'Token {token}', 'Content-Type': 'application/json'},
    json={"command": f'unzip -o ~/deploy_env.zip -d ~/ && pip3 install -r ~/deploy_env/requirements.txt'}
)
print("Bash unzip response:", bash.status_code, bash.content)

# Run bot
print("Launching bot...")
run = requests.post(
    f'https://www.pythonanywhere.com/api/v0/user/{username}/bash_tasks/',
    headers={'Authorization': f'Token {token}', 'Content-Type': 'application/json'},
    json={"command": "cd ~/deploy_env && export $(cat .env | xargs) && nohup python3 main.py &"}
)
print("Run bot response:", run.status_code, run.content)
EOF
