name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up deploy env
        run: |
          mkdir -p deploy_env
          cp -r * deploy_env/
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> deploy_env/.env
          echo "VIDEO_STORAGE=${{ secrets.VIDEO_STORAGE }}" >> deploy_env/.env
          zip -r deploy_env.zip deploy_env

      - name: Write deploy.py
        run: |
          cat > deploy.py <<EOF
import requests

username = '${{ secrets.PA_USERNAME }}'
token = '${{ secrets.PA_TOKEN }}'

# Upload zip to PythonAnywhere
with open('deploy_env.zip', 'rb') as f:
    r = requests.post(
        f'https://www.pythonanywhere.com/api/v0/user/{username}/files/path/home/{username}/deploy_env.zip',
        headers={'Authorization': f'Token {token}'},
        files={'file': f}
    )
    print('Upload:', r.status_code, r.text)

# Unzip + install
cmd1 = "unzip -o ~/deploy_env.zip -d ~/ && pip3 install -r ~/deploy_env/requirements.txt"
r1 = requests.post(
    f'https://www.pythonanywhere.com/api/v0/user/{username}/bash_tasks/',
    headers={'Authorization': f'Token {token}', 'Content-Type': 'application/json'},
    json={"command": cmd1}
)
print('Install:', r1.status_code, r1.text)

# Run bot
cmd2 = "cd ~/deploy_env && export $(cat .env | xargs) && nohup python3 main.py &"
r2 = requests.post(
    f'https://www.pythonanywhere.com/api/v0/user/{username}/bash_tasks/',
    headers={'Authorization': f'Token {token}', 'Content-Type': 'application/json'},
    json={"command": cmd2}
)
print('Run bot:', r2.status_code, r2.text)
EOF

      - name: Install dependencies and run deploy
        run: |
          pip install requests
          python3 deploy.py
