name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: telescopy-bot
          service-name: telescopy-bot
          service-env: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            VIDEO_STORAGE=${{ secrets.VIDEO_STORAGE }}
          type: git
          git-url: git@github.com:${{ github.repository }}.git
          git-branch: main
          org-name: ${{ secrets.KOYEB_ORGANIZATION_NAME }}
          api-token: ${{ secrets.KOYEB_API_TOKEN }}
